hospital_system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

lab_staffs/urls.py
from django.urls import path
from . import views

app_name = 'lab_staffs'

urlpatterns = [
    path('', views.home, name='home'),
    path('viewdiagnosis/', views.viewDiagnosis, name='viewDiagnosis'),
    path('viewdiagnosis/approveordeny/', views.approve_or_deny, name='approve_deny'),
    path('createreport/', views.createReport, name='createReport'),
    path('deleteandupdatereport/', views.deleteAndUpdateReport, name='deleteAndUpdateReport'),
    path('viewreport/', views.viewReport, name='viewReport'),
    path('updatereport/<int:id>', views.updateReport, name='updateReport'),
    path('profile/', views.profile, name='profile'),
]

secure_hospital_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('hospital/', include('hospital.urls')),
    path('patients/', include('patients.urls')),
    path('doctors/', include('doctors.urls')),
    path('hospital-staffs/', include('hospital_staffs.urls')),
    path('lab-staffs/', include('lab_staffs.urls')),
    path('insurance-staffs/', include('insurance_staffs.urls')),
    path('administrators/', include('administrators.urls')),
    path('chatbot/', include('chatbot.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='users-home'),
    path('login/<str:usertype>', views.login_user, name='login-user'),
    # path('verify/<str:usertype>', views.verify_user, name='verify-user'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/', views.profile_user, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

lab_staffs/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class LabStaffProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}'

lab_staffs/forms.py
from django.forms import ModelForm, forms
from hospital.models import LabTest, Diagnosis


class LabTestCreateForm(ModelForm):
    class Meta:
        model = LabTest
        fields = ('diagnosis', 'lab_test_report')

    def __init__(self, *args, **kwargs):
        super(LabTestCreateForm, self).__init__(*args, **kwargs)
        self.fields['diagnosis'].queryset = Diagnosis.objects.filter(lab_test_status__isnull=True,
                                                                     lab_tests_recommended__isnull=False)

    def clean_diagnosis(self):
        diagnosis = self.cleaned_data['diagnosis']
        exist = LabTest.objects.filter(diagnosis=diagnosis).exists()

        if exist:
            raise forms.ValidationError('lab test already exist')

        return diagnosis


class LabTestUpdateForm(ModelForm):
    class Meta:
        model = LabTest
        fields = ['lab_test_report']

lab_staffs/views.py
from django.http import HttpResponse

from users.forms import UserUpdateForm
from users.models import User

import logging
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from users.decorators import lab_staff_required
from hospital.models import Diagnosis, LabTest
from patients.models import PatientProfile
from .forms import LabTestCreateForm, LabTestUpdateForm

logger = logging.getLogger(__name__)


@login_required
@lab_staff_required
# Create your views here.
def home(request):
    logger.info(f"Inside home of {request.user}")
    return redirect('lab_staffs:viewDiagnosis')


@login_required
@lab_staff_required
def viewDiagnosis(request):
    logger.info('lab staff viewing diagnosis')
    diagnosis = Diagnosis.objects.filter(lab_test_status__isnull=True, lab_tests_recommended__isnull=False)
    context = {'diagnosis': diagnosis}
    return render(request, "lab_staffs/viewDiagnosis.html", context)


@login_required
@lab_staff_required
def approve_or_deny(request):
    if request.POST:
        if 'Approve' in request.POST:
            logger.info('lab staff approve lab test')
            messages.success(request, 'Lab test report approved!')
            return redirect('lab_staffs:createReport')
        elif 'Deny' in request.POST:
            logger.info('lab staff deny labtest')
            appid = request.POST.get('app_id')
            username = request.POST.get('dia')
            user = User.objects.get(username=username)
            patientProfile = PatientProfile.objects.get(user=user)
            userDia = Diagnosis.objects.get(patient=patientProfile, appointment_id=appid)
            userDia.lab_test_status = False
            userDia.save()
            messages.info(request, 'Lab test report denied!')
    return redirect('lab_staffs:viewDiagnosis')


@login_required
@lab_staff_required
def viewReport(request):
    logger.info('lab staff viewing report')
    reports = LabTest.objects.all()
    context = {'reports': reports}
    return render(request, "lab_staffs/viewReport.html", context)


@login_required
@lab_staff_required
def createReport(request):
    if request.POST:
        createReportForm = LabTestCreateForm(request.POST)
        if createReportForm.is_valid():
            lab_test_data = createReportForm.cleaned_data
            lab_test_data['patient'] = lab_test_data.get('diagnosis').patient
            lab_test_data['doctor'] = lab_test_data.get('diagnosis').doctor

            lab_tes_obj = LabTest(**lab_test_data)
            lab_tes_obj.save()
            lab_tes_obj.diagnosis.lab_test_status = True
            lab_tes_obj.diagnosis.save()

            messages.success(request, f"Lab Test created for {lab_test_data['patient']}")
            return redirect('lab_staffs:home')
        else:
            messages.error(request, f"Please check the input data")
            return redirect('lab_staffs:createReport')
    else:
        createReportForm = LabTestCreateForm()
    context = {'createReportForm': createReportForm}
    return render(request, "lab_staffs/createReport.html", context)


@login_required
@lab_staff_required
def deleteAndUpdateReport(request):
    if request.POST:
        if 'Delete' in request.POST:
            dia_id = request.POST.get('dia_id')
            lab_test_deleted = LabTest.objects.get(diagnosis_id=dia_id)
            lab_test_deleted.delete()
            logger.info('lab staff delete report')
            return redirect('lab_staffs:viewReport')
        elif 'Update' in request.POST:
            dia_id = request.POST.get('dia_id')
            lab_test_update = LabTest.objects.get(diagnosis_id=dia_id)
            lab_test_update_form = LabTestUpdateForm(instance=lab_test_update)
            context = {'updateReportForm': lab_test_update_form,
                       'dia_id': dia_id}
            return render(request, 'lab_staffs/updateReport.html', context)
    return redirect('lab_staffs:viewReport')


@login_required
@lab_staff_required
def updateReport(request, id):
    lab_test_update = LabTest.objects.get(diagnosis_id=id)
    if request.POST:
        print(lab_test_update)
        update_form = LabTestUpdateForm(request.POST, instance=lab_test_update)
        if update_form.is_valid():
            update_form.save()
            logger.info('lab staff update report')
            return redirect('lab_staffs:viewReport')
        return HttpResponse('form unvalid')
    return redirect('lab_staffs:viewReport')


@login_required
@lab_staff_required
def profile(request):
    print("Inside lab_staff profile")
    user = request.user

    if request.method == 'POST':
        print("Request type: POST")
        u_form = UserUpdateForm(request.POST, instance=user)

        if u_form.is_valid():
            u_form.save()

            messages.success(request, f'Your account has been updated!')
            return redirect('doctors:profile')
    else:
        print(f"Request type: GET")
        u_form = UserUpdateForm(instance=user)

    context = {
        'u_form': u_form,
    }

    return render(request, 'lab_staffs/profile.html', context)

lab_staffs/templates/lab_staffs/approve_or_deny.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
{% endif %}
{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/createReport.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
<div class="container">
    <h1>New Lab Test Report</h1>
    <form method="POST" novalidate>
        {% csrf_token %}

        <div class="row">
            <div class="col">
                {{ createReportForm | crispy }}
            </div>
        </div>
        <br>
        <div class="col-md-2 col-md-offset-10">
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
    </form>
</div>
{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/deleteAndUpdateReport.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}

{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/labstaff-home.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
<h1>Lab Staff Home</h1>
{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/main.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body-content %}

<div class="container">

    <div class="row my-5">

        <div class="col-md-3">
            <div class="content-section">
                <h3>Menu</h3>

                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_staffs:viewDiagnosis' %}">View Diagnosis</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_staffs:createReport' %}">Create Report</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_staffs:viewReport' %}">View Test Report</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-9">
            {% block labstaffcontent %}{% endblock labstaffcontent %}
        </div>

    </div>
</div>

    <script type="text/javascript" src="{% static 'doctors/script.js' %}"></script>
</body>

</html>


{% endblock body-content %}

lab_staffs/templates/lab_staffs/profile.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}

    <div class="content-section">
        <!-- FORM HERE -->
        <form method="POST" action="">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
            </fieldset>
            <div class="form-group">
                <br>
                <button class="btn btn-outline-info" type="submit">Update Profile</button>
            </div>
        </form>
    </div>

{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/updateReport.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
<h1>Update Lab Test Report</h1>
{% if updateReportForm %}
    <form method="POST" action="{% url 'lab_staffs:updateReport' dia_id%}">
        {% csrf_token %}

        <div class="row">
            <div class="col">
                {{ updateReportForm | crispy }}
            </div>
        </div>
        <br>
        <input name="submit" type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endif %}
{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/viewDiagnosis.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
<h3>View Diagnosis</h3>
{% if diagnosis %}
    <table class="table">
        <thead>
        <th scope="col">Patient</th>
        <th scope="col">Doctor</th>
        <th scope="col">Recommended Lab Tests</th>
        <th scope="col">Status</th>
        </thead>
        <tbody>
        {% for dia in diagnosis %}
            <tr>
            <form id="approve-options" method="POST" action="{% url 'lab_staffs:approve_deny' %}">
                {% csrf_token %}
                <td>{{ dia.patient }}</td>
                <td>{{ dia.doctor }} </td>
                <td>{{ dia.lab_tests_recommended }}</td>
                <td>
                <input name="dia" type="hidden" onclick="" value="{{ dia.patient.user }}">
                <input name="app_id" type="hidden" value="{{ dia.appointment_id }}">
                <input name="Approve" type="submit" class="btn btn-success" value="Approve">
                <input name="Deny" type="submit" class="btn btn-danger" onclick="" value="Deny">
                </td>
            </form>
            </tr>

        {% endfor %}
        </tbody>
    </table>
{% else %}
    <h4>No Diagnosis found</h4>
{% endif %}

{% endblock labstaffcontent %}

lab_staffs/templates/lab_staffs/viewReport.html
{% extends 'lab_staffs/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block labstaffcontent %}
    <h3>View Report</h3>
    {% if reports %}
        <table class="table">
            <thead>
            <th scope="col">Patient</th>
            <th scope="col">Doctor</th>
            <th scope="col">Lab Test</th>
            <th scope="col">Report</th>
            <th scope="col">Update/Delete</th>
            </thead>
            <tbody>
            {% for report in reports %}
                <tr>
                    <form id="Delete-update-options" method="POST"
                          action="{% url 'lab_staffs:deleteAndUpdateReport' %}">
                        {% csrf_token %}
                        <td>{{ report.diagnosis.patient }}</td>
                        <td>{{ report.diagnosis.doctor }}</td>
                        <td>{{ report.diagnosis.lab_tests_recommended }}</td>
                        <td>{{ report.lab_test_report }}</td>
                        <td>
                            <input name="dia_id" type="hidden" value="{{ report.diagnosis_id }}">
                            <input name="Update" type="submit" class="btn btn-success" value="Update">
                            <input name="Delete" type="submit" class="btn btn-danger" value="Delete">
                        </td>
                    </form>
                </tr>

            {% endfor %}
            </tbody>
        </table>


    {% else %}
        <h4>No Report found</h4>
    {% endif %}

{% endblock labstaffcontent %}