hospital_staffs/urls.py
from django.urls import path
from . import views

app_name = 'hospital_staffs'

urlpatterns = [
    path('', views.home, name='home'),
    path('createPatient/', views.createPatient, name='createPatient'),
    path('viewPatient/', views.viewPatient, name='viewPatient'),
    path('viewRecords/', views.viewRecords, name='viewRecords'),
    path('viewLabRecords/', views.viewLabTests, name='viewLabRecords'),
    path('createTransaction/', views.createTransaction, name='createTransaction'),
    path('approveTransaction/', views.approveTransaction, name='approveTransaction'),
    path('approveAppointment/', views.approveAppointment, name='approveAppointment'),
    path('Appointment/', views.appointment, name='Appointment'),
    path('profile/', views.profile, name='profile'),

]

hospital_system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

secure_hospital_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('hospital/', include('hospital.urls')),
    path('patients/', include('patients.urls')),
    path('doctors/', include('doctors.urls')),
    path('hospital-staffs/', include('hospital_staffs.urls')),
    path('lab-staffs/', include('lab_staffs.urls')),
    path('insurance-staffs/', include('insurance_staffs.urls')),
    path('administrators/', include('administrators.urls')),
    path('chatbot/', include('chatbot.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='users-home'),
    path('login/<str:usertype>', views.login_user, name='login-user'),
    # path('verify/<str:usertype>', views.verify_user, name='verify-user'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/', views.profile_user, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hospital_staffs/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class HospitalStaffProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}'

hospital_staffs/forms.py
from django.forms import ModelForm
from django.apps import apps
from django.db.models import Q

from hospital.models import Appointment, Diagnosis


class CreatePatientForm(ModelForm):
    class Meta:
        model = apps.get_model('hospital', 'Diagnosis')
        fields = ('appointment',)

    def __init__(self, ids, *args, **kwargs):
        super(CreatePatientForm, self).__init__(*args, **kwargs)
        self.fields['appointment'].queryset = Appointment.objects.filter(Q(status=True) & ~Q(id__in=ids))


class ViewPatientForm(ModelForm):
    class Meta:
        model = apps.get_model('hospital', 'Diagnosis')
        fields = ('patient',)


class ViewPatientRecords(ModelForm):
    class Meta:
        model = apps.get_model('hospital', 'Diagnosis')
        fields = ('patient',)


class CreateTransaction(ModelForm):
    class Meta:
        model = apps.get_model('hospital', 'Transaction')
        fields = ('diagnosis', 'amount')

    def __init__(self, *args, **kwargs):
        super(CreateTransaction, self).__init__(*args, **kwargs)
        self.fields['diagnosis'].queryset = Diagnosis.objects.filter(transaction__isnull=True)


class ViewLabRecords(ModelForm):
    class Meta:
        model = apps.get_model('hospital', 'LabTest')
        fields = ('patient',)


class ViewAppointment(ModelForm):
    class Meta:
        model = apps.get_model('hospital', 'Appointment')
        fields = ('doctor',)

hospital_staffs/views.py
from random import randint

import requests
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from doctors.models import DoctorProfile
from hospital.models import Diagnosis, Appointment, Transaction
from users.decorators import hospital_staff_required
from .forms import CreatePatientForm, ViewPatientForm, ViewPatientRecords, CreateTransaction, ViewLabRecords, \
    ViewAppointment
from django.contrib import messages
from django.apps import apps
from users.forms import UserUpdateForm


@login_required
@hospital_staff_required
def home(request):
    return render(request, 'hospital_staffs/home.html')


@login_required
@hospital_staff_required
def createPatient(request):
    all_diagnosis = Diagnosis.objects.all()
    ids = [d.appointment.id for d in all_diagnosis]
    form = CreatePatientForm(ids)
    model1 = apps.get_model('hospital', 'Appointment')
    model2 = apps.get_model('hospital', 'Diagnosis')
    print(form.fields)
    if request.method == 'POST':
        try:
            flag = request.POST['appointment']
            y = model1.objects.get(id=flag)
            x = model2.objects.create(appointment=y, doctor=y.doctor, patient=y.patient)
            x.save()
            messages.success(request, 'New Record Created')
        except KeyError:
            print('KeyError')
        except Exception as e:
            print('some issue')
    context = {'form': form}
    return render(request, 'hospital_staffs/createPatient.html', context)


@login_required
@hospital_staff_required
def viewPatient(request):
    form = ViewPatientForm()
    context = {'form': form, 'prescription': [],
               'diagnosis': [], 'checklistP': False, 'checklistD': False}
    if request.method == 'GET' and 'patient' in request.GET:
        form = ViewPatientForm(request.GET)
        if form.is_valid():
            model = apps.get_model('hospital', 'Diagnosis')
            try:
                x = model.objects.filter(patient=request.GET['patient'])
                context['prescription'] = []
                context['diagnosis'] = []
                for i in x.iterator():
                    if (i.prescription):
                        context['prescription'].append(i.prescription)
                    if (i.details):
                        context['diagnosis'].append(i.details)
                if (context['prescription']):
                    context['checklistP'] = True
                if (context['diagnosis']):
                    context['checklistD'] = True


            except Exception as e:
                context['prescription'] = ["No information available as of now"]
                context['diagnosis'] = ["No information available as of now"]
            finally:
                render(request, 'hospital_staffs/viewPatient.html', context)

    return render(request, 'hospital_staffs/viewPatient.html', context)


@login_required
@hospital_staff_required
def viewRecords(request):
    form = ViewPatientRecords()
    defText = 'Enter Patient Details fo records'
    context = {'form': form, 'records': [], 'checklist': False}
    if request.method == 'GET' and 'patient' in request.GET:
        form = ViewPatientRecords(request.GET)
        if form.is_valid():
            model = apps.get_model('hospital', 'Diagnosis')
            try:
                x = model.objects.filter(patient=request.GET['patient'])
                context['records'] = []
                for i in x.iterator():
                    l = ['', '', '', '']
                    l[0], l[1], l[2], l[3] = i.prescription, i.details, i.doctor, i.lab_tests_recommended
                    context['records'].append(l)
                    context['checklist'] = True
            except Exception as e:
                context['records'] = ["No information available as of now"]
            finally:
                render(request, 'hospital_staffs/viewPatientRecords.html', context)
    return render(request, 'hospital_staffs/viewPatientRecords.html', context)


@login_required
@hospital_staff_required
def viewLabTests(request):
    form = ViewLabRecords()
    context = {'form': form, 'records': [], 'checklist': False}
    if request.method == 'GET' and 'patient' in request.GET:
        form = ViewLabRecords(request.GET)
        if form.is_valid():
            model = apps.get_model('hospital', 'LabTest')
            try:
                x = model.objects.filter(patient=request.GET['patient'])
                context['records'] = []
                for i in x.iterator():
                    l = ['', '', '']
                    l[0], l[1], l[2] = i.doctor, i.lab_test_report, i.created
                    context['records'].append(l)
                    context['checklist'] = True
            except Exception as e:
                context['records'] = ["No information available as of now"]
            finally:
                render(request, 'hospital_staffs/viewLabRecords.html', context)
    return render(request, 'hospital_staffs/viewLabRecords.html', context)


@login_required
@hospital_staff_required
def createTransaction(request):
    model = apps.get_model('hospital_staffs', 'HospitalStaffProfile')
    x = model.objects.filter(user=request.user.id)
    val = 0
    for i in x.iterator():
        val = i.id
        break
    form = CreateTransaction()
    if request.method == 'POST':
        form = CreateTransaction(request.POST)
        if form.is_valid():
            transaction_data = form.cleaned_data
            transaction_data['patient'] = transaction_data.get('diagnosis').patient
            transaction_obj = Transaction(**transaction_data)
            transaction_obj.save()

            messages.success(request, 'New Transaction Created')
    context = {'form': form}
    return render(request, 'hospital_staffs/createTransaction.html', context)


@login_required
@hospital_staff_required
def approveTransaction(request):
    model = apps.get_model('hospital', 'Transaction')
    context = {'transactions': []}
    if request.method == 'POST':
        try:
            flag = request.POST['id']
            y = model.objects.get(id=flag)
            y.completed = True
            y.save()
            generateHreq(y, request)
            messages.success(request, 'Transaction completed!')
            print(flag)
        except KeyError:
            print('KeyError')
    try:
        x = model.objects.filter(approved='t', completed=None)
        for i in x.iterator():
            context['transactions'].append(i)
    except:
        context['transactions'] = [['Record not found'] * 3]
    return render(request, 'hospital_staffs/approveTransaction.html', context)


@login_required
@hospital_staff_required
def approveAppointment(request):
    model = apps.get_model('hospital', 'Appointment')
    context = {'transactions': []}
    if request.method == 'POST':
        try:
            flag = request.POST['id']
            y = model.objects.get(id=flag)
            y.status = True
            if y.doctor is None:
                y.doctor = DoctorProfile.objects.first()
            y.save()
            messages.success(request, 'Appointment Approved!')
            print(flag)
        except KeyError:
            print('KeyError')
    try:
        x = model.objects.filter(status=None)
        for i in x.iterator():
            context['transactions'].append(i)
    except:
        context['transactions'] = []
    return render(request, 'hospital_staffs/approveAppointment.html', context)


@login_required
@hospital_staff_required
def appointment(request):
    form = ViewAppointment()
    context = {
        'appointments': [],
        'form': form
    }
    if request.method == 'GET' and 'doctor' in request.GET:
        form = ViewAppointment(request.GET)
        if form.is_valid():
            model = apps.get_model('hospital', 'Appointment')
            try:
                x = model.objects.filter(doctor=request.GET['doctor'], status='t')
                context['appointments'] = x
            except Exception as e:
                print(e)
            finally:
                render(request, 'hospital_staffs/appointments.html', context)
    return render(request, 'hospital_staffs/appointments.html', context=context)


@login_required
@hospital_staff_required
def profile(request):
    print("Inside hospitalstaff profile")
    user = request.user

    if request.method == 'POST':
        print("Request type: POST")
        u_form = UserUpdateForm(request.POST, instance=user)

        if u_form.is_valid():
            u_form.save()

            messages.success(request, f'Your account has been updated!')
            return redirect('doctors:profile')
    else:
        print(f"Request type: GET")
        u_form = UserUpdateForm(instance=user)

    context = {
        'u_form': u_form,
    }

    return render(request, 'hospital_staffs/profile.html', context)


def generateHreq(y, request):
    try:
        URL = 'http://ec2-54-176-204-18.us-west-1.compute.amazonaws.com:8080/api/addcar'
        value = randint(0, 100000)
        inval = 'CAR' + str(value)
        r = requests.post(url=URL, json={'carid': inval, 'make': str(y.patient), 'model': str(y.amount),
                                         'colour': str(request.user), 'owner': 'djangoapp'})
        print(inval)
    except Exception as e:
        print(e)

hospital_staffs/templates/hospital_staffs/appointments.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}


<form action="" method="get">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>View Appointments</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>
		
		<br>

<div class="row my-3">
    <div class="col">
        {% if appointments %}
        <table class="table">
            <thead>
                <!-- <th scope="col">S.No.</th> -->
                <th scope="col">Status</th>
                <th scope="col">Description</th>
                <th scope="col">Patient</th>
                <th scope="col">Scheduled Date</th>
            </thead>
            <tbody>
                {% for app in appointments %}
                <tr>
                    <td>{{ app.status|yesno:"Accepted,Declined,Pending" }}</td>
                    <td>{{ app.appointment_details }}</td>
                    <td>{{ app.patient.user.username }}</td>
                    <td>{{ app.scheduled_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Appointments found!</h4>
        {% endif %}

    </div>
</div>

{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/approveAppointment.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}


<h4> Records: </h4>

<table class="table">
            <thead>
                <th scope="col">Record</th>
                <th scope="col">Appointment Details </th>
                <th scope="col">Patient Id</th>
                <th scope="col">Doctor Id</th>
				<th scope="col">Scheduled Date</th>
				<th scope="col">Approve</th>
            </thead>
            <tbody>
                {% for i in transactions %}
                <tr>
				
					<form id="myform{{ forloop.counter }}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="id" value={{i.id}} />
							<td>{{ forloop.counter}}</td>
							<td>{{ i.appointment_details }}</td>
							<td>{{ i.patient }}</td>

							<td>{{ i.doctor }}</td>
							<td>{{ i.scheduled_date }}</td>
							<td><a href="{% url 'hospital_staffs:approveAppointment' %}" onclick="document.forms[{{ forloop.counter0 }}].submit();return false;">Approve</a></td>
					  </form>
                </tr>
                {% endfor %}
            </tbody>
        </table>





{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/approveTransaction.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}


<h4> Records: </h4>

<table class="table">
            <thead>
                <th scope="col">Record</th>
                <th scope="col">Amount</th>
                <th scope="col">Patient Id</th>
                <th scope="col">Diagnosis</th>
				<th scope="col">Approve</th>
            </thead>
            <tbody>
                {% for i in transactions %}
                <tr>
				
					<form id="myform{{ forloop.counter }}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="id" value={{i.id}} />
							<td>{{ forloop.counter}}</td>
							<td>{{ i.amount }}</td>
							<td>{{ i.patient }}</td>
							<td>{{ i.diagnosis}}</td>
							<td><a href="{% url 'hospital_staffs:approveTransaction' %}" onclick="document.forms[{{ forloop.counter0 }}].submit();return false;">Approve</a></td>
					  </form>
                </tr>
                {% endfor %}
            </tbody>
        </table>





{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/createPatient.html
{% extends 'hospital_staffs/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}



        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>Create New Patient Record</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>





{% endblock patientcontent %}

hospital_staffs/templates/hospital_staffs/home.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body-content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'patients/styles.css' %}">
    <title>Document</title>
</head>

<body>

    <div class="container">

        <div class="row my-5">

            <div class="col-md-3">
                <div class="content-section">
                    <h3>Menu</h3>
                    <!-- <ul class="list-group patient-sidebar">
                        <li id="home" onclick="switchPage('home')">Home</li>
                        <li id="appointments" onclick="switchPage('appointments')">Appointments</li>
                        <li id="diagnosis" onclick="switchPage('diagnosis')">
                            Diagnosis</li>
                        <li id="prescriptions" onclick="switchPage('prescriptions')">Prescriptions</li>
                        <li id="reports" onclick="switchPage('reports')">
                            Reports</li>
                        <li id="insurance" onclick="switchPage('insurance')">
                            Insurance</li>
                        <li id="transactions" onclick="switchPage('transactions')">Transactions</li>
                        <li id="profile" onclick="switchPage('profile')">My Profile</li>
                    </ul> -->
                    <ul class="nav flex-column">
                        <li class="nav-item"> <a class="nav-link"  href="{% url 'hospital_staffs:createPatient' %}">Create Patient Records</a></li>
                      <li class="nav-item"><a class="nav-link"  href="{% url 'hospital_staffs:viewPatient' %}">View Patient Diagnosis and Prescription</a></li>
                      <li class="nav-item"><a  class="nav-link"  href="{% url 'hospital_staffs:viewRecords' %}">View Patient Records</a></li>
					  <li class="nav-item"><a class="nav-link"  href="{% url 'hospital_staffs:viewLabRecords' %}">View Lab Records</a></li>
                      <li class="nav-item"> <a  class="nav-link" href="{% url 'hospital_staffs:createTransaction' %}">Create Transactions</a></li>
					  <li class="nav-item"> <a  class="nav-link" href="{% url 'hospital_staffs:approveTransaction' %}">Approve Transactions</a></li>					  
                   	  <li class="nav-item"> <a  class="nav-link" href="{% url 'hospital_staffs:approveAppointment' %}">Approve Appointments</a></li>
					  <li class="nav-item"> <a  class="nav-link" href="{% url 'hospital_staffs:Appointment' %}">View Appointments</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-9">
                {% block patientcontent %}{% endblock patientcontent %}

                <!-- <div id="home-view" style="display:none;">
                    <h2>Home</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="appointments-view" style="display:none;">
                    <h2>Appointments</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="diagnosis-view" style="display:none;">
                    <h2>Diagnosis</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="prescriptions-view" style="display:none;">
                    <h2>Prescriptions</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="reports-view" style="display:none;">
                    <h2>Reports</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="insurance-view" style="display:none;">
                    <h2>Insurance</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="transactions-view" style="display:none;">
                    <h2>Transactions</h2>
                    {% for appointment in appointments %}
                    <article class="media content-section">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                                <small class="text-muted">{{ appointment.date_posted }}</small>
                            </div>
                            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
                            <p class="article-content">{{ appointment.description }}</p>
                        </div>
                    </article>
                    {% endfor %}
                </div>

                <div id="profile-view" style="display:none;">
                    <h2>Profile</h2>
                    <div class="content-section">
                        <div class="media">
                            <img class="rounded-circle account-img" src="{{ user.patientprofile.image.url }}" alt="">
                            <div class="media-body">
                                <h2 class="account-heading">{{ user.username }}</h2>
                                <p class="text-secondary">{{ user.email }}</p>
                            </div>
                        </div>
                        FORM HERE
                        <form name="profile-form" method="POST" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ pform | crispy }}
                            <div class="row">
                                <div class="col">
                                    <img src="{{ profile.user.patientprofile.image.url }}" alt="Profile Image Not Found!"
                                        style="width: 100px; aspect-ratio: 1;">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label for="username" class="form-label">Username</label>
                                    <input id="username" class="form-control" name="username" type="text" value="{{ profile.user.username }}" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label for="email" class="form-label">Email</label>
                                    <input id="email" class="form-control" name="email" type="text" value="{{ profile.user.email }}" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label for="address" class="form-label">Address</label>
                                    <input id="address" name="address" type="text" class="form-control" value="{{ profile.address }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <label for="insurance" class="form-label">Insurance</label>
                                    <input id="insurance" name="insurance" type="text" class="form-control" value="{{ profile.insurance }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col"></div>
                            </div>
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Profile Info</legend>
                                {{ u_form|crispy }}
                                {{ p_form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Update Profile</button>
                            </div>
                        </form>
                    </div>
                </div> -->



            </div>

        </div>
    </div>


    <script type="text/javascript" src="{% static 'patients/script.js' %}"></script>
</body>

</html>


{% endblock body-content %}