administrators/urls.py
from django.urls import path
from . import views

app_name = 'administrators'

urlpatterns = [
    path('', views.base, name='home'),
    path('home/', views.base, name='home'),
    path('transactions/', views.transactions, name='transactions'),
    path('employees/', views.employees, name='employees'),
    path('employees/<str:username>/', views.employees_detail, name='employees-detail'),
    path('profile/', views.profile, name='profile'),
    path('log/', views.log, name='log')
]

hospital_system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

secure_hospital_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('hospital/', include('hospital.urls')),
    path('patients/', include('patients.urls')),
    path('doctors/', include('doctors.urls')),
    path('hospital-staffs/', include('hospital_staffs.urls')),
    path('lab-staffs/', include('lab_staffs.urls')),
    path('insurance-staffs/', include('insurance_staffs.urls')),
    path('administrators/', include('administrators.urls')),
    path('chatbot/', include('chatbot.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='users-home'),
    path('login/<str:usertype>', views.login_user, name='login-user'),
    # path('verify/<str:usertype>', views.verify_user, name='verify-user'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/', views.profile_user, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

administrators/models.py
from django.db import models
from django.conf import settings


class AdministratorProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}'

administrators/views.py
from django.contrib.auth import get_user_model
from django.db.models import Q

from hospital.models import Transaction
from users.forms import UserUpdateForm, UserRegisterForm
from users.models import Log
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from users.decorators import administrator_required
from django.apps import apps
from django.core.paginator import Paginator

User = get_user_model()


@login_required
@administrator_required
def base(request):
    return redirect('administrators:employees')


@login_required
@administrator_required
def transactions(request):
    # model = apps.get_model('hospital', 'Transaction')
    context = {'transactions': []}
    if request.method == 'POST':
        try:
            flag = request.POST['id']
            y = Transaction.objects.get(id=flag)
            y.approved = True
            y.save()
            print(flag)
        except KeyError:
            print('KeyError')
    try:
        x = Transaction.objects.filter(approved=None, completed=None)
        for i in x.iterator():
            context['transactions'].append(i)
    except:
        context['transactions'] = [['Record not found'] * 3]
    return render(request, 'administrators/transactions.html', context)


@login_required
@administrator_required
def log(request):
    all_logs = Log.objects.all().order_by('-date')
    paginator = Paginator(all_logs, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'administrators/log.html', {'logs': page_obj})


@login_required
@administrator_required
def employees(request):
    print('Inside employees view')
    form = UserRegisterForm()

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Account created for {username}!')

            return redirect('administrators:employees')
        else:
            messages.error(request, 'An error occurred during registration')

    employees = User.objects.filter(
        Q(user_type='doctor') | Q(user_type='insurance_staff') | Q(user_type='lab_staff') | Q(
            user_type='hospital_staff') | Q(user_type='administrator')).order_by('user_type', 'username')

    paginator = Paginator(employees, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'form': form,
        'employees': page_obj,
    }

    return render(request, 'administrators/employees.html', context=context)


@login_required
@administrator_required
def employees_detail(request, username):
    print('Inside employee detail view')
    user = User.objects.get(username=username)

    if request.method == 'POST':
        print("Request type: POST")
        u_form = UserUpdateForm(request.POST, instance=user)

        print(f'post data: {request.POST}')
        if 'delete_employee' in request.POST:
            print(f'Deleting employee {username}')
            user.delete()

            messages.info(request, f'Employee: {username} has been deleted!')
            return redirect('administrators:employees')

        if u_form.is_valid():
            u_form.save()

            messages.success(request, f'Employee: {username} has been updated!')
            return redirect('administrators:employees-detail', username=username)
    else:
        print(f"Request type: GET")
        u_form = UserUpdateForm(instance=user)

    context = {
        'u_form': u_form,
    }
    return render(request, 'administrators/employee_detail.html', context)


@login_required
@administrator_required
def profile(request):
    print("Inside Administrator profile")
    user = request.user

    if request.method == 'POST':
        print("Request type: POST")
        u_form = UserUpdateForm(request.POST, instance=user)

        if u_form.is_valid():
            u_form.save()

            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        print(f"Request type: GET")
        u_form = UserUpdateForm(instance=user)

    context = {
        'u_form': u_form,
    }

    return render(request, 'administrators/profile.html', context)

administrators/templates/administrators/employee_detail.html
{% extends 'administrators/main.html' %}
{% load crispy_forms_tags %}

{% block admincontent %}

    <div class="content-section">
        <!-- FORM HERE -->
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
            </fieldset>
            <br>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" name="update_employee">Update Employee</button>
                <button class="btn btn-outline-danger" type="submit" name="delete_employee">Delete Employee</button>
            </div>
        </form>
    </div>

{% endblock admincontent %}

administrators/templates/administrators/employees.html
{% extends 'administrators/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block admincontent %}

    <div class="row mb-3">
        <div class="col">
            <h2>Employees</h2>
        </div>
        <div class="col text-end">
            <button class="btn btn-info" onclick="newEmployee()">Create New User</button>
        </div>

    </div>

    <div class="row my-3 d-none" id="new-employee-block">
        <div class="col">

            <form action="" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col">
                        <h3>Create New User</h3>
                    </div>
                    <div class="col text-end">
                        <button class="btn btn-primary">Submit</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        {{ form | crispy }}
                    </div>
                </div>
            </form>

        </div>
    </div>

    <div class="row my-3">
        <div class="col">
            {% if employees %}
                <table class="table">
                    <thead>
                    <th scope="col">Department</th>
                    <th scope="col">Username</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    </thead>
                    <tbody>
                    {% for user in employees %}
                        <tr>
                            <td>{{ user.user_type|upper }}</td>
                            <td>
                                <a href="{% url 'administrators:employees-detail' user.username %}">{{ user.username }}</a>
                            </td>
                            {% if user.first_name %}
                                <td>{{ user.first_name }}</td>
                            {% else %}
                                <td><em>-</em></td>
                            {% endif %}
                            {% if user.first_name %}
                                <td>{{ user.last_name }}</td>
                            {% else %}
                                <td><em>-</em></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>No Employees found!</h4>
            {% endif %}

        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {% if employees.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ employees.previous_page_number }}">Previous</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
            </li>
          {% endif %}
          {% for i in employees.paginator.page_range %}
            {% if employees.number == i %}
              <li class="page-item active" aria-current="page">
                <span class="page-link">
                  {{ i }}
                  <span class="sr-only"></span>
                </span>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if employees.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ employees.next_page_number }}">Next</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
            </li>
          {% endif %}
        </ul>
      </nav>

{% endblock admincontent %}

administrators/templates/administrators/log.html
{% extends 'administrators/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block admincontent %}

    <div class="row mb-3">
        <div class="col">
            <h2>User Logs</h2>
        </div>
    </div>

    <div class="row my-3">
        <div class="col">
            {% if logs %}
                <table class="table">
                    <thead>
                    <th scope="col">S No</th>
                    <th scope="col">Username</th>
                    <th scope="col">Usertype</th>
                    <th scope="col">Login Timestamp</th>
                    </thead>
                    <tbody>
                    {% for log in logs %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ log.user }}</td>
                            <td>{{ log.user.user_type }}</td>
                            <td>{{ log.date }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h5><i>No Logs Found!</i></h5>
            {% endif %}

        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {% if logs.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ logs.previous_page_number }}">Previous</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
            </li>
          {% endif %}
          {% for i in logs.paginator.page_range %}
            {% if logs.number == i %}
              <li class="page-item active" aria-current="page">
                <span class="page-link">
                  {{ i }}
                  <span class="sr-only"></span>
                </span>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if logs.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ logs.next_page_number }}">Next</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
            </li>
          {% endif %}
        </ul>
      </nav>
{% endblock admincontent %}

administrators/templates/administrators/main.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block additional-styles %}
    <link rel="stylesheet" href="{% static 'administrators/styles.css' %}">
{% endblock additional-styles %}

{% block body-content %}

    <div class="container">
        <div class="row my-5">

            <div class="col-md-3">
                <div class="content-section">
                    <h3>Admin Menu</h3>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'administrators:employees' %}">Employees Portal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'administrators:transactions' %}">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'administrators:log' %}">Logs</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-md-9">
                {% block admincontent %}{% endblock admincontent %}
            </div>

        </div>
    </div>

{% endblock body-content %}

{% block additional-scripts %}
    <script type="text/javascript" src="{% static 'administrators/script.js' %}"></script>
{% endblock additional-scripts %}

administrators/templates/administrators/profile.html
{% extends 'administrators/main.html' %}
{% load crispy_forms_tags %}

{% block admincontent %}

    <div class="content-section">
        <!-- FORM HERE -->
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
            </fieldset>
            <br>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update Profile</button>
            </div>
        </form>
    </div>

{% endblock admincontent %}

administrators/templates/administrators/transactions.html
{% extends 'administrators/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block admincontent %}

<div class="row mb-3">
    <div class="col">
        <h2>Transactions</h2>
    </div>
</div>

<div class="row my-3">
    <div class="col">
        {% if transactions %}
            <table class="table">
                <thead>
                    <th scope="col">Record</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Patient Id</th>
                    <th scope="col">Diagnosis</th>
                    <th scope="col">Approve</th>
                </thead>
                <tbody>
                    {% for i in transactions %}
                    <tr>
                        <form id="myform{{ forloop.counter }}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="id" value={{i.id}} />
                                <td>{{ forloop.counter}}</td>
                                <td>{{ i.amount }}</td>
                                <td>{{ i.patient }}</td>
                                <td>{{ i.diagnosis}}</td>
                                <td><a href="{% url 'administrators:transactions' %}" onclick="document.forms[{{ forloop.counter0 }}].submit();return false;">Approve</a></td>
                          </form>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h5><i>No Transactions Found!</i></h5>
        {% endif %}

    </div>
</div>
{% endblock admincontent %}