hospital_system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'

urlpatterns = [
    path('', views.home, name='home'),
    path('appointments/', views.appointments, name='appointments'),
    path('diagnosis/', views.diagnosis, name='diagnosis'),
    path('prescriptions/', views.prescriptions, name='prescriptions'),
    path('lab_test_reports/', views.lab_test_reports, name='lab-test-reports'),
    path('insurance/', views.insurance, name='insurance'),
    path('transactions/', views.transactions, name='transactions'),
    path('verify/<str:hfunc>', views.verify_patient, name='verify-patient'),
    path('profile/', views.profile, name='profile'),
    path('requestPolicy/', views.requestPolicy, name='requestPolicy'),
    path('receipt/', views.receipt, name='receipt')
]

secure_hospital_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('hospital/', include('hospital.urls')),
    path('patients/', include('patients.urls')),
    path('doctors/', include('doctors.urls')),
    path('hospital-staffs/', include('hospital_staffs.urls')),
    path('lab-staffs/', include('lab_staffs.urls')),
    path('insurance-staffs/', include('insurance_staffs.urls')),
    path('administrators/', include('administrators.urls')),
    path('chatbot/', include('chatbot.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='users-home'),
    path('login/<str:usertype>', views.login_user, name='login-user'),
    # path('verify/<str:usertype>', views.verify_user, name='verify-user'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/', views.profile_user, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

patients/models.py
from django.db import models
from django.conf import settings


class PatientProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return f'{self.user.username}'

patients/forms.py
from django import forms

from doctors.models import DoctorProfile
from hospital.models import Appointment, InsuredPatient, InsuranceClaim, Transaction, InsuranceRequest, Diagnosis


class AppointmentForm(forms.ModelForm):
    doctor = forms.ModelChoiceField(label="Select Doctor (Optional)",
                                    required=False, queryset=DoctorProfile.objects.all())
    scheduled_date = forms.DateTimeField(label='Please choose a date',
                                         widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    class Meta:
        model = Appointment

        fields = ('doctor', 'scheduled_date', 'appointment_details')


class InsuredPatientForm(forms.ModelForm):
    class Meta:
        model = InsuredPatient
        fields = ['insurance_policy']


class InsuranceClaimForm(forms.ModelForm):
    class Meta:
        model = InsuranceClaim
        fields = ('claim_amount', 'diagnosis')

    def __init__(self, patient, *args, **kwargs):
        super(InsuranceClaimForm, self).__init__(*args, **kwargs)
        self.fields['diagnosis'].queryset = Diagnosis.objects.filter(patient=patient, insuranceclaim__isnull=True)


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ('diagnosis', 'amount', 'approved', 'completed')


class InsuranceRequestForm(forms.ModelForm):
    class Meta:
        model = InsuranceRequest
        fields = ('insurance_policy',)

patients/views.py
import ast
import logging

import requests
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

from hospital.models import Appointment, Diagnosis, LabTest, InsuranceClaim, Transaction, InsurancePolicy, \
    InsuranceRequest
from patients.forms import AppointmentForm, InsuranceClaimForm, TransactionForm, InsuredPatientForm, \
    InsuranceRequestForm
from secure_hospital_system import settings
from users.decorators import patient_required
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import get_user_model

from users.forms import UserUpdateForm, CodeForm

User = get_user_model()

logger = logging.getLogger(__name__)


@login_required
@patient_required
def home(request):
    print(f"Inside home of {request.user}")
    return redirect('patients:appointments')


@login_required
@patient_required
def appointments(request):
    print(f"{request.user}: Appointments page")
    if request.method == 'POST':
        form = AppointmentForm(request.POST)

        if form.is_valid():
            appointment_data = form.cleaned_data
            appointment_data['patient'] = request.user.patientprofile

            print(f"{request.user}: New appointment details- {appointment_data}")
            appointment_obj = Appointment(**appointment_data)
            appointment_obj.save()

            messages.success(request, 'New Appointment Requested')
            return redirect('patients:appointments')
        else:
            messages.error(request, 'Error Processing Request. Please re-check your inputs')
            print(f"{request.user}: Invalid form data- {form.data}")
    else:
        form = AppointmentForm()

    context = {
        'appointments': Appointment.objects.filter(patient=request.user.patientprofile),
        'form': form
    }
    return render(request, 'patients/appointments.html', context=context)


@login_required
@patient_required
def diagnosis(request):
    print(f"{request.user}: Diagnosis page")

    diagnosis_list = Diagnosis.objects.filter(patient=request.user.patientprofile)
    print(f"{request.user}: Previous diagnosis: {diagnosis_list}")

    context = {
        'diagnosis_list': diagnosis_list,
    }
    return render(request, 'patients/diagnosis.html', context=context)


@login_required
@patient_required
def prescriptions(request):
    print(f"{request.user}: Prescriptions page")

    diagnosis_list = Diagnosis.objects.filter(patient=request.user.patientprofile)
    print(f"{request.user}: Previous diagnosis: {diagnosis_list}")

    context = {
        'diagnosis_list': diagnosis_list,
    }
    return render(request, 'patients/prescriptions.html', context=context)


@login_required
@patient_required
def lab_test_reports(request):
    print(f"{request.user}: Lab Test Reports page")

    lab_tests = LabTest.objects.filter(patient=request.user.patientprofile)
    print(f"{request.user}: Previous Lab Reports: {lab_tests}")

    context = {
        'lab_tests': lab_tests,
    }
    return render(request, 'patients/lab_test_reports.html', context=context)


@login_required
@patient_required
def insurance(request):
    print(f"{request.user}: Insurance page")
    if request.session.get('code', '00000') != request.user.code.number:
        return redirect('patients:verify-patient', hfunc='insurance')

    patient_profile = request.user.patientprofile
    insured_patient = None
    if hasattr(patient_profile, 'insuredpatient'):
        insured_patient = request.user.patientprofile.insuredpatient

    if request.method == 'POST':
        form = InsuranceClaimForm(patient_profile, request.POST)
        if form.is_valid():
            insurance_claim_data = form.cleaned_data
            if insured_patient:
                insurance_claim_data['insured_patient'] = insured_patient

                insurance_claim_obj = InsuranceClaim(**insurance_claim_data)
                insurance_claim_obj.save()

                messages.success(request, 'New Insurance Claim Filed')
            else:
                print(f"{request.user}: Patient not insured. Only God can save you!!")
                messages.error(request, 'Patient not insured. Only God can save you!!')

            return redirect('patients:insurance')
        else:
            print(f"{request.user}: Invalid insurance form data- {form.data}")
    else:
        form = InsuranceClaimForm(patient_profile)

    context = {
        'form': form
    }

    if insured_patient:
        context['insurance_claims'] = InsuranceClaim.objects.filter(insured_patient=insured_patient)

    return render(request, 'patients/insurance.html', context=context)


@login_required
@patient_required
def transactions(request):
    print(f"{request.user}: Transactions page")
    # if request.session.get('code', '00000') != request.user.code.number:
    #     return redirect('patients:verify-patient', hfunc='transactions')
    #
    # if request.method == 'POST':
    #     form = TransactionForm(request.POST)
    #     if form.is_valid():
    #         data = form.cleaned_data
    #         messages.success(request, 'Transaction complete')
    #         return redirect('patients:transactions')
    # else:
    #     form = TransactionForm()
    #
    # context = {
    #     'transactions': Transaction.objects.filter(patient=request.user.patientprofile),
    #     'form': form
    # }
    #
    # return render(request, 'patients/transactions.html', context=context)
    return redirect('patients:receipt')


def verify_patient(request, hfunc):
    form = CodeForm(request.POST or None)
    pk = request.session.get('pk')

    if pk:
        user = User.objects.get(pk=pk)
        code = user.code
        code_user = f"{user.username}: {user.code}"

        if not request.POST:
            # send email
            send_otp_through_email(user, code)
            print(code_user)

        if form.is_valid():
            num = form.cleaned_data.get('number')

            if str(code) == num:
                code.save()
                request.session['code'] = str(code)
                messages.success(request, f'{user.username} Verification Successful!')
                return redirect(f'patients:{hfunc}')
            else:
                messages.error(request, f'Incorrect OTP!! Please try again.')
                return redirect(f'patients:{hfunc}')
    else:
        messages.warning(request, "Internal Server Error. Try logging-in Again...")
        return redirect('patients:home')

    messages.info(request, "If you don't receive OTP, please verify/update your Email in profile page")
    return render(request, 'users/verify.html', {'form': form})


def send_otp_through_email(user, otp):
    try:
        send_mail(subject="Dr. Yau's Clinic Email Verification Code", message=f"OTP: {otp}",
                  from_email=settings.EMAIL_HOST_USER, recipient_list=[user.email])
    except:
        print(f"Unable to send OTP to {user.email}! Please update correct Email in Profile")


@login_required
@patient_required
def profile(request):
    print("Inside patient profile")
    user = request.user
    patient_profile = request.user.patientprofile

    if request.method == 'POST':
        print("Request type: POST")
        u_form = UserUpdateForm(request.POST, instance=user)
        i_form = InsuredPatientForm(request.POST, instance=patient_profile.insuredpatient)

        if u_form.is_valid() and i_form.is_valid():
            u_form.save()
            i_form.save()

            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        print(f"Request type: GET")
        u_form = UserUpdateForm(instance=user)
        i_form = InsuredPatientForm()

        if hasattr(patient_profile, 'insuredpatient'):
            print(f"{patient_profile} has the 'insuredpatient' attribute")
            i_form = InsuredPatientForm(instance=patient_profile.insuredpatient)

    context = {
        'u_form': u_form,
        'i_form': i_form,
    }

    return render(request, 'patients/profile.html', context)


# @login_required
# @patient_required
# def requestPolicy(request):
#    form = InsuredPatientForm()
#    user = request.user.patientprofile
#    if request.method == 'POST':
#        try:
#            form = InsuredPatientForm(request.POST)
#            flag = request.POST['insurance_policy']
#            policy = InsurancePolicy.objects.get(id=flag)
#            amount = policy.max_amount
#            if form.is_valid():
#                if hasattr(user, 'insuredpatient'):
#                    insured_patient = request.user.patientprofile.insuredpatient
#                    insured_patient.insurance_policy = policy
#                    insured_patient.amount_available = amount
#                else:
#                    insured_patient = InsuredPatient(patient=user,
#                                             insurance_policy=policy, amount_available=amount)
#                insured_patient.save()
#                y = insured_patient
#                print(y.amount_available)
#                messages.success(request, 'Record Updated')
#        except Exception as e:
#            print(e)
#    context = {'form': form}
#    return render(request, 'patients/requestPolicy.html', context)

@login_required
@patient_required
def requestPolicy(request):
    form = InsuranceRequestForm(instance=request.user.patientprofile.insuredpatient)
    user = request.user.patientprofile
    if request.method == 'POST':
        try:
            form = InsuranceRequestForm(request.POST)
            if form.is_valid():
                policy = InsurancePolicy.objects.get(id=request.POST['insurance_policy'])
                req = InsuranceRequest(patient=user, insurance_policy=policy, approved=False)
                req.save()
                messages.success(request, 'Record Created')
        except Exception as e:
            print(e)

patients/templates/patients/appointments.html
{% extends 'patients/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}

<div class="row mb-3">
    <div class="col">
        <h2>Appointments</h2>
    </div>
    <div class="col text-end">
        <button class="btn btn-info" onclick="newAppointment()">Create New Appointment</button>
    </div>
</div>

<div class="row my-3 d-none" id="new-appointment-block">
    <div class="col">

        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>Create New Appointment</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>

    </div>
</div>

<div class="row my-3">
    <div class="col">
        {% if appointments %}
        <table class="table">
            <thead>
                <th scope="col">Status</th>
                <th scope="col">Description</th>
                <th scope="col">Doctor</th>
                <th scope="col">Scheduled Date</th>
            </thead>
            <tbody>
                {% for app in appointments %}
                <tr>
                    <td>{{ app.status|yesno:"Accepted,Declined,Pending" }}</td>
                    <td>{{ app.appointment_details }}</td>
                    {% if app.doctor %}
                        <td>Dr. {{ app.doctor.user.username }}</td>
                    {% else %}
                        <td><em>-Not Assigned Yet-</em></td>
                    {% endif %}
                    <td>{{ app.scheduled_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>No Previous Appointments!</h4>
        {% endif %}

    </div>
</div>

{% endblock patientcontent %}

patients/templates/patients/diagnosis.html
{% extends 'patients/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}

    <div class="row mb-3">
        <div class="col">
            <h2>Diagnosis Summary</h2>
        </div>
    </div>

    <div class="row my-3">
        <div class="col">
            {% if diagnosis_list %}
                <table class="table">
                    <thead>
                    <th scope="col">Doctor</th>
                    <th scope="col">Comments</th>
                    <th scope="col">Prescription</th>
                    <th scope="col">Lab-Tests Recommended</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Date</th>
                    </thead>
                    <tbody>
                    {% for d in diagnosis_list %}
                        <tr>
                            <!-- Check to find assigned doctor -->
                            {% if d.doctor %}
                                <td>Dr. {{ d.doctor.user.username }}</td>
                            {% else %}
                                <td><em>-Not Assigned Yet-</em></td>
                            {% endif %}

                            <td>{{ d.details }}</td>
                            <td>{{ d.prescription }}</td>

                            <!-- Check to find whether lab-tests are assigned -->
                            <td>{{ d.lab_test_status|yesno:"Yes,Yes,No" }}</td>

                            <!-- Check to find transaction amount -->
                            <td>${{ d.amount }}</td>
                            <td>{{ d.created }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>No Diagnosis found</h4>
            {% endif %}

        </div>
    </div>

{% endblock patientcontent %}

patients/templates/patients/home.html
{% extends 'patients/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}


<div class="container">

    <h2>Home</h2>
    {% for appointment in appointments %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ appointment.doctor }}</a>
                <small class="text-muted">{{ appointment.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ appointment.title }}</a></h2>
            <p class="article-content">{{ appointment.description }}</p>
        </div>
    </article>
    {% endfor %}

</div>


{% endblock patientcontent %}

patients/templates/patients/insurance.html
{% extends 'patients/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}

    <div class="row mb-3">
        <div class="col">
            <h2>Insurance Claims</h2>
        </div>
        <div class="col text-end">
            <button class="btn btn-info" onclick="newInsuranceBlock()">Raise Insurance Claim</button>
        </div>
    </div>

    <div class="row my-3 d-none" id="new-insurance-block">
        <div class="col">

            <form action="" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col">
                        <h3>Raise New Insurance Claim</h3>
                    </div>
                    <div class="col text-end">
                        <button class="btn btn-primary">Submit</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        {{ form | crispy }}
                    </div>
                </div>
            </form>

        </div>
    </div>

    <div class="row my-3">
        <div class="col">
            {% if insurance_claims %}
                <table class="table">
                    <thead>
                    <th scope="col">Diagnosis Date</th>
                    <th scope="col">Claim Amount</th>
                    <th scope="col">Status</th>
                    </thead>
                    <tbody>
                    {% for ins in insurance_claims %}
                        {% if ins.status == None %}
                            <tr class="table-warning">
                        {% elif ins.status %}
                            <tr class="table-success">
                        {% elif not ins.status %}
                            <tr class="table-danger">
                        {% endif %}
                            <td>{{ ins.diagnosis.appointment.scheduled_date }}</td>
                            <td>{{ ins.claim_amount }}</td>
                            <td>{{ ins.status|yesno:"Accepted,Rejected,Pending" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>No Insurance Claim Records found</h4>
            {% endif %}

        </div>
    </div>

{% endblock patientcontent %}

patients/templates/patients/lab_test_reports.html
{% extends 'patients/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}

    <div class="row mb-3">
        <div class="col">
            <h2>Lab Test Reports</h2>
        </div>
    </div>

    <div class="row my-3">
        <div class="col">
            {% if lab_tests %}
                <table class="table">
                    <thead>
                    <th scope="col">Recommended By</th>
                    <th scope="col">Tests</th>
                    <th scope="col">Reports</th>
                    <th scope="col">Date</th>
                    </thead>
                    <tbody>
                    {% for lt in lab_tests %}
                        <tr>
                            <td>Dr. {{ lt.doctor.user.username }}</td>
                            <td>{{ lt.diagnosis.lab_tests_recommended }}</td>
                            <td>{{ lt.lab_test_report }}</td>
                            <td>{{ lt.created }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>No Reports found</h4>
            {% endif %}

        </div>
    </div>

{% endblock patientcontent %}

patients/templates/patients/main.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body-content %}

    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'patients/styles.css' %}">
        <title>Document</title>
    </head>

    <body>

    <div class="container">
        <div class="row my-5">

            <div class="col-md-3">
                <div class="content-section">
                    <h3>Menu</h3>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'patients:appointments' %}">Appointments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'patients:diagnosis' %}">Diagnosis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'patients:prescriptions' %}">Prescriptions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'patients:lab-test-reports' %}">Lab Test Reports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'patients:insurance' %}">Insurance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'patients:transactions' %}">Transactions</a>
                        </li>
						<li class="nav-item">
                            <a class="nav-link" href="{% url 'patients:requestPolicy' %}">Request New Policy</a>
                        </li>
						<li class="nav-item">
                            <a class="nav-link" href="{% url 'patients:receipt' %}">Receipts</a>
                        <li class="nav-item">
                            <a class="nav-link"  href="#" onclick="return popitup('/chatbot')">Chatbot</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-md-9">
                {% block patientcontent %}{% endblock patientcontent %}
            </div>

        </div>
    </div>


    <script type="text/javascript" src="{% static 'patients/script.js' %}"></script>
    </body>

    </html>


{% endblock body-content %}

patients/templates/patients/prescriptions.html
{% extends 'patients/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}

    <div class="row mb-3">
        <div class="col">
            <h2>Prescriptions</h2>
        </div>
    </div>

    <div class="row my-3">
        <div class="col">
            {% if diagnosis_list %}
                <table class="table">
                    <thead>
                    <th scope="col">Prescription</th>
                    <th scope="col">Prescribed By</th>
                    <th scope="col">Date</th>
                    </thead>
                    <tbody>
                    {% for d in diagnosis_list %}
                        <tr>
                            <td>{{ d.prescription }}</td>
                            <td>Dr. {{ d.doctor.user.username }}</td>
                            <td>{{ d.created }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>No Previous Prescriptions Found!</h4>
            {% endif %}

        </div>
    </div>

{% endblock patientcontent %}

patients/templates/patients/profile.html
{% extends 'patients/main.html' %}
{% load crispy_forms_tags %}

{% block patientcontent %}

    <div class="content-section">
        <!-- FORM HERE -->
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ i_form|crispy }}
            </fieldset>
            <br>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update Profile</button>
            </div>
        </form>
    </div>

{% endblock patientcontent %}

patients/templates/patients/receipt.html
{% extends 'patients/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}

    <div class="row mb-3">
        <div class="col">
            <h2>Receipts</h2>
        </div>
    </div>
	<table class="table">
            <thead>
                <th scope="col">Record</th>
                <th scope="col">Amount</th>
                <th scope="col">Patient Id</th>
                <th scope="col">Diagnosis</th>
            </thead>
            <tbody>
                {% for i in transactions %}
                <tr>
				
					<form id="myform{{ forloop.counter }}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="id" value={{i.id}} />
							<td>{{ forloop.counter}}</td>
							<td>{{ i.amount }}</td>
							<td>{{ i.patient }}</td>
							<td>{{ i.diagnosis}}</td>
					  </form>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    

{% endblock patientcontent %}

patients/templates/patients/requestPolicy.html
{% extends 'patients/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}


<form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h3>Request New Policy</h3>
                </div>
                <div class="col text-end">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {{ form | crispy }}
                </div>
            </div>
        </form>
		
{% endblock patientcontent %}

patients/templates/patients/transactions.html
{% extends 'patients/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block patientcontent %}

    <div class="row mb-3">
        <div class="col">
            <h2>Transactions</h2>
        </div>
    </div>

    <div class="row my-3">
        <div class="col">
            {% if transactions %}
                <table class="table">
                    <thead>
                    <th scope="col">Diagnosis Date</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Payment complete</th>
                    <th scope="col">Final Status</th>
                    </thead>
                    <tbody>
                    {% for t in transactions %}
                        {% if t.completed == None %}
                            <tr class="table-warning">
                        {% elif t.approved %}
                            <tr class="table-success">
                        {% elif not t.completed %}
                            <tr class="table-danger">
                        {% endif %}
                            <td>{{ t.diagnosis.appointment.scheduled_date }}</td>
                            <td>{{ t.diagnosis.amount }}</td>
                            <td>{{ t.approved|yesno:"Yes,No,Due" }}</td>
                            <td>{{ t.completed|yesno:"Completed,Incomplete,---" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>No Transaction Records found</h4>
            {% endif %}

        </div>
    </div>

{% endblock patientcontent %}